# Python Unit Tests & Static Analysis
# This workflow runs unit tests and static code analysis
name: Python Tests and Static Analysis

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run unit tests
        run: PYTHONPATH=. pytest --cov=src/ --cov-report=xml
      - name: Run mypy static analysis
        run: PYTHONPATH=. mypy src/ --ignore-missing-imports --exclude="src/llm/router.py"
