# spelling.yml is blocked per https://github.com/check-spelling/check-spelling/security/advisories/GHSA-g86g-chm8-7r2p
name: Spell checking

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request_target:
    branches:
      - "**"
    types:
      - "opened"
      - "reopened"
      - "synchronize"
  issue_comment:
    types:
      - "created"

jobs:
  spelling:
    name: Check Spelling
    permissions:
      contents: read
      pull-requests: read
      actions: read
      security-events: write
    outputs:
      followup: ${{ steps.spelling.outputs.followup }}
    runs-on: ubuntu-latest
    if: ${{ contains(github.event_name, 'pull_request') || github.event_name == 'push' }}
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: check-spelling
        id: spelling
        uses: check-spelling/check-spelling@v0.0.25
        with:
          suppress_push_for_open_pull_request: ${{ github.actor != 'dependabot[bot]' && 1 }}
          checkout: true
          check_file_names: 1
          spell_check_this: ${{ github.repository }}@${{ github.ref }}
          post_comment: 0
          use_magic_file: 1
          report-timing: 1
          warnings: bad-regex,binary-file,deprecated-feature,ignored-expect-variant,large-file,limited-references,no-newline-at-eof,noisy-file,non-alpha-in-dictionary,token-is-substring,unexpected-line-ending,whitespace-in-dictionary,minified-file,unsupported-configuration,no-files-to-check,unclosed-block-ignore-begin,unclosed-block-ignore-end
          experimental_apply_changes_via_bot: ${{ github.repository_owner == 'SoftwareDevLabs' && 1 }}
          use_sarif: 1
          check_extra_dictionaries: ""
          dictionary_source_prefixes: >
            {
            "cspell": "https://raw.githubusercontent.com/check-spelling/cspell-dicts/v20241114/dictionaries/"
            }
          extra_dictionaries: |
            cspell:software-terms/softwareTerms.txt
            cspell:cpp/stdlib-cpp.txt
            cspell:cpp/stdlib-c.txt
            cspell:python/python/python-lib.txt
            cspell:php/php.txt
            cspell:node/node.txt
            cspell:dart/dart.txt
            cspell:filetypes/filetypes.txt
            cspell:java/java.txt
            cspell:css/css.txt
            cspell:dotnet/dotnet.txt
            cspell:npm/npm.txt
            cspell:fullstack/fullstack.txt
            cspell:java/java-terms.txt
            cspell:r/r.txt
            cspell:golang/go.txt
            cspell:cpp/stdlib-cmath.txt
            cspell:typescript/typescript.txt
            cspell:html/html.txt
            cspell:cpp/compiler-msvc.txt
            cspell:django/django.txt
            cspell:aws/aws.txt
            cspell:python/common/extra.txt
            cspell:cpp/ecosystem.txt
            cspell:cpp/lang-keywords.txt
            cspell:csharp/csharp.txt
            cspell:cpp/compiler-clang-attributes.txt
            cspell:python/python/python.txt
            cspell:mnemonics/mnemonics.txt
            cspell:powershell/powershell.txt
      - name: Upload SARIF report
        uses: actions/upload-artifact@v4
        with:
          name: check-spelling-sarif
          path: check-spelling.sarif

  comment-push:
    name: Report (Push)
    runs-on: ubuntu-latest
    needs: spelling
    permissions:
      actions: read
      contents: write
    if: (success() || failure()) && needs.spelling.outputs.followup && github.event_name == 'push'
    steps:
      - name: comment
        uses: check-spelling/check-spelling@v0.0.25
        with:
          checkout: true
          spell_check_this: ${{ github.repository }}@${{ github.ref }}
          task: ${{ needs.spelling.outputs.followup }}

  comment-pr:
    name: Report (PR)
    runs-on: ubuntu-latest
    needs: spelling
    permissions:
      actions: read
      contents: read
      pull-requests: write
    if: (success() || failure()) && needs.spelling.outputs.followup && contains(github.event_name, 'pull_request')
    steps:
      - name: comment
        uses: check-spelling/check-spelling@v0.0.25
        with:
          checkout: true
          spell_check_this: ${{ github.repository }}@${{ github.ref }}
          task: ${{ needs.spelling.outputs.followup }}
          experimental_apply_changes_via_bot: ${{ github.repository_owner == 'SoftwareDevLabs' && 1 }}

  update:
    name: Update PR
    permissions:
      contents: write
      pull-requests: write
      actions: read
    runs-on: ubuntu-latest
    if: ${{
      github.repository_owner == 'SoftwareDevLabs' &&
      github.event_name == 'issue_comment' &&
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '@check-spelling-bot apply') &&
      contains(github.event.comment.body, 'https://')
      }}
    concurrency:
      group: spelling-update-${{ github.event.issue.number }}
      cancel-in-progress: false
    steps:
      - name: apply spelling updates
        uses: check-spelling/check-spelling@v0.0.25
        with:
          experimental_apply_changes_via_bot: ${{ github.repository_owner == 'SoftwareDevLabs' && 1 }}
          checkout: true
          # ssh_key: "${{ secrets.CHECK_SPELLING }}"
